//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "api_key")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub key_hash: String,
    pub created_at: DateTime,
    pub expires_at: DateTime,
    pub is_revoked: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::archive_user::Entity",
        from = "Column::UserId",
        to = "super::archive_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ArchiveUser,
}

impl Related<super::archive_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchiveUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
