//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "crawl_status")]
pub enum CrawlStatus {
    #[sea_orm(string_value = "bad_crawl")]
    BadCrawl,
    #[sea_orm(string_value = "complete")]
    Complete,
    #[sea_orm(string_value = "error")]
    Error,
    #[sea_orm(string_value = "pending")]
    Pending,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "metadata_format")]
pub enum MetadataFormat {
    #[sea_orm(string_value = "wacz")]
    #[serde(rename = "wacz")]
    Wacz,
}
#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "researcher")]
    Researcher,
}
